#!/usr/bin/python

import optparse, os, sys, ConfigParser, getpass, re, urlparse, time, shutil

VERSION = '0.7'


def get_directories(config, dir_type):
  """
  Get read or write directories and return formatted list
  """
  
  if (config.has_option('Directories', dir_type) and 
      config.get('Directories', dir_type) != ''):
    directories = config.get('Directories', dir_type).split(',')
    directories = map(lambda x: x.strip(), directories)
    return directories
  else:
    return []
  

def prefix_base(base_dir, path):
  
  if path == '/':
    return base_dir
  elif path[0] == '/':
    return os.path.join(base_dir, path[1:])
  return os.path.join(base_dir, path)
  
def get_chirp_host():
  """
  Get chirp host information
  """
  chirp_dir = os.path.expanduser('~/.chirp')
  options = open(os.path.join(chirp_dir, 'chirp_options')).read().strip()
  match = re.search('CHIRP_HOST=\s*(\w.*)', options)
  if match is None:
    sys.stderr.write("Can't get chirp host, has SkeletonKey been installed?")
    sys.exit(1)
  if not os.path.exists(os.path.join(chirp_dir, 'chirp.port')):
    sys.stderr.write("Can't get chirp port, has chirp been started?")
    sys.exit(1)
  port = open(os.path.join(chirp_dir, 'chirp.port')).read().strip()
  return "%s:%s" % (match.group(1), port)
  
  
def generate_xrootd_args(config):
  """
  Generate xrootd specific arguments for parrot_run based on config file
  """
  return ""

def set_cvmfs_key(cvmfs_options, key):
  """
  Set CVMFS pubkey option in cvmfs_options string, replacing current key if 
  present
  """
  key_file = urlparse.urlparse(key)[2].split('/')[-1]
  if 'pubkey' not in cvmfs_options:
    return cvmfs_options + ",pubkey=" + key_file
  
  options = ""
  for opt in cvmfs_options.split(','):
    if 'pubkey' in opt:
      options += ",pubkey=" + key_file
    else:
      options += "," + opt 
  # Return options minus the leading , 
  return options[1:]

def parse_cvmfs_options(config):
  """
  Parse CVMFS options and generate a dict containing CVMFS info
  """
  cvmfs_info = {}
  keys = []
  if not config.has_section('CVMFS'):
    return cvmfs_info
  
  repo_num = 1
  while True:
    repo_opt = "repo%s" % repo_num
    if not config.has_option('CVMFS', repo_opt):
      # no more repos to add
      break
    repo_name = config.get('CVMFS', repo_opt)
    cvmfs_info[repo_name] = {}
    opt_name = "repo%s_key" % repo_num
    if config.has_option('CVMFS', opt_name):
      cvmfs_info[repo_name]['key'] = config.get('CVMFS', opt_name)
    else:
      sys.stderr.write("Missing %s in CVMFS section\n" % opt_name)
      sys.exit(1)
      
    opt_name = "repo%s_options" % repo_num
    if config.has_option('CVMFS', opt_name):
      cvmfs_options = config.get('CVMFS', opt_name)
      cvmfs_options = set_cvmfs_key(cvmfs_options, cvmfs_info[repo_name]['key'])
      cvmfs_info[repo_name]['options'] = cvmfs_options
    else:
      sys.stderr.write("Missing %s in CVMFS section\n" % opt_name)
      sys.exit(1)
    repo_num += 1
    
  return cvmfs_info

def reset_acls(base_dir, read_dirs, write_dirs):
  """
  Check and reset acls in directories as needed
  """
  for dir_name in read_dirs:
    if dir_name[0] == '/':
      acl_name = os.path.join(base_dir, dir_name[1:], '.__acl')
    else:
      acl_name = os.path.join(base_dir, dir_name, '.__acl') 
    if not os.path.exists(acl_name):
      shutil.copy(os.path.expanduser('~/.chirp/acl'),
                  acl_name)

    if not os.path.exists(acl_name):
      shutil.copy(os.abspath('~/.chirp/acl'),
                  acl_name)
  for dir_name in write_dirs:
    if dir_name[0] == '/':
      acl_name = os.path.join(base_dir, dir_name[1:], '.__acl')
    else:
      acl_name = os.path.join(base_dir, dir_name, '.__acl') 
    if not os.path.exists(acl_name):
      shutil.copy(os.path.expanduser('~/.chirp/acl'),
                  acl_name)

def create_chirp_ticket(config):
  """
  Create a chirp ticket with the appropriate permissions and return
  a string with ticket 
  """
  if not config.has_section('Directories'):
    return ""
    
  ticket = ""
  chirp_host = get_chirp_host()
  read_directories = get_directories(config, 'read')
  write_directories = get_directories(config, 'write')
  ticket_call = "chirp %s ticket_create -output myticket.ticket " \
                "-bits 1024 -duration 86400 " % chirp_host
  base_dir = config.get('Directories', 'export_base')
  reset_acls(base_dir, read_directories, write_directories)
  for directory in read_directories:
    ticket_call += " %s rl " % directory
    
  for directory in write_directories:
    ticket_call += " %s rwl " % directory
    
    
  retcode = os.system(ticket_call)
  if os.WEXITSTATUS(retcode) != 0:
    sys.stderr.write("Can't create ticket\n")
    return None
  ticket = open('myticket.ticket').read().replace('"', r'\"')  
  os.unlink('myticket.ticket')
  return ticket

def parse_args(job_args):
  """
  Parse string with job arguments into a list for inclusion in job wrapper
  """
  args = []
  if job_args == "":
    return args
  tokens = job_args.split(' ')
  double_quotes = False
  single_quotes = False
  cur_token = ''
  for token in tokens:
    if not double_quotes and not single_quotes:
      if token[0] not in ('"', "'"):
        args.append(token)
        cur_token = ''
      elif token[0] == '"':
        double_quotes = True
        cur_token = token[1:]
      elif token[0] == "'":
        single_quotes = True
        cur_token = token[1:]
    elif double_quotes:
      if token[-1] != '"':
        cur_token += " %s" % token
      elif token[-2:] == '\\"':
        cur_token += " %s\"" % token[:-2]        
      else:
        cur_token += " %s" % token[:-1]
        args.append(cur_token)
        cur_token = ''
        double_quotes = False
    elif single_quotes:
      if token[-1] != "'":
        cur_token += " %s" % token
      elif token[-2:] == "\\'":
        cur_token += " %s'" % token[:-2]
      else:
        cur_token += " %s" % token[:-1]
        args.append(cur_token)
        cur_token = ''
        single_quotes = False
  return args

def get_wrapper_template():
  """
  Check the parrot config and get the wrapper template based on that
  """
  wrapper_location = None
  config = ConfigParser.SafeConfigParser()
  config.read(os.path.expanduser('~/.skeletonkey.config'))
  if (config.has_section('Installation') and
      config.has_option('Installation', 'location')):
    wrapper_location =  os.path.join(config.get('Installation', 'location'), 
                                     'templates',
                                     'run_job.py')
  else:
    sys.stderr.write("Can't find location of wrapper template\n")
    sys.exit(1)
  if (not os.path.exists(wrapper_location) or 
      not os.path.isfile(wrapper_location)):
    sys.stderr.write("Wrapper template not in specified " \
                     "location: %s\n" % wrapper_location)
    sys.exit(1)
  return open(wrapper_location).read()

def create_job_wrapper(output_file, config):
  """Generate a job wrapper"""
  try:
    template = get_wrapper_template()
    chirp_ticket = create_chirp_ticket(config)
    if chirp_ticket is None:
      sys.stderr.write("Error occurred when generating ticket, exiting...\n")
      return False
    template = template.replace('%%%TICKET%%%', 
                                chirp_ticket)
    if (config.has_option('Application', 'http_proxy') and 
        config.get('Application', 'http_proxy') != ''):
      template = template.replace('%%%WEB_PROXY%%%', 
                                   config.get('Application', 'http_proxy'))
    else:
      template = template.replace('%%%WEB_PROXY%%%', '')

    if (not config.has_section('Parrot') or 
        not (config.has_option('Parrot', 'location') and 
             config.get('Parrot', 'location') != '')):
      template = template.replace('%%%PARROT_URL%%%', 
                                  config.get('Parrot', 'location'))
    else:
      template = template.replace('%%%PARROT_URL%%%', 
                                  'http://uc3-data.uchicago.edu/parrot')
    if (config.has_section('Application') and
        config.has_option('Application', 'location') and 
        config.get('Application', 'location') != ''):
      template = template.replace('%%%APP_URL%%%', 
                                  config.get('Application', 'location'))
    else:
      template = template.replace('%%%APP_URL%%%',  '""')
    template = template.replace('%%%JOB_SCRIPT%%%', 
                                config.get('Application', 'script'))
    if (config.has_section('Application') and 
        (config.has_option('Application', 'arguments') and 
         config.get('Application', 'arguments') != '')):
      template = template.replace('%%%JOB_ARGS%%%', 
                                  parse_args(config.get('Application', 
                                                        'arguments')))
    else:
      template = template.replace('%%%JOB_ARGS%%%',  '""')
    
    template = template.replace('%%%CVMFS_INFO%%%',
                                str(parse_cvmfs_options(config)))
  
    if config.has_section('Directories'):
      template = template.replace('%%%CHIRP_MOUNT%%%',
                                  "/chirp/%s" % get_chirp_host())
    open(output_file, 'w').write(template)
    os.chmod(output_file, 0700)
  except IOError, ex:
    sys.stderr.write("Got exception when writing wrapper:\n%s\n" % ex)
    return False
  return True

if __name__ == '__main__':
  parser = optparse.OptionParser(usage='Usage: %prog [options] arg1 arg2', 
                                 version='%prog ' + VERSION)
  
  parser.add_option('-o',
                    '--output',
                    action='store',
                    dest='output_file',
                    default='run_job.py',
                    help='Name of job wrapper file generated ')
  parser.add_option('-c',
                    '--config-file',
                    action='store',
                    dest='config_file',
                    default='',
                    help='Configuration file to use')
  
  (options, args) = parser.parse_args()
  
  if options.config_file == '':
    parser.exit(msg='Must give a config file')
  
  if (not os.path.exists(options.config_file) or 
      not os.path.isfile(options.config_file)):
    sys.stderr.write("Config file %s not found, " \
                     "exiting...\n" % options.config_file)
    sys.exit(1)
  
  config = ConfigParser.SafeConfigParser()
  config.read(options.config_file)
  
  if not config.has_option('Application', 'script'):
    sys.stderr.write("Must give an script to run\n")
    sys.exit(1)

  
  if not create_job_wrapper(options.output_file, config):
    sys.stderr.write("Can't write job wrapper\n")
    sys.exit(1)

